defaults:
  - _self_

map_path: "data/NAIP/m_3907736_se_18_1_20170628.jpg"
particles_num: 100
patch_size: 63
traj_len: 100
trajectory_type: 'sine'
visualize: False
noise_scale_den: 5000
convergence_threshold_var: 100.0
error_threshold_px: 10.0
required_converged_steps: 50
conv_wrong_place: 50

pre_selection: True
matcher: "NN"
encoder_name: "resnet50"
embedding_size: 128
weights_path: "data/models/model_365.pth"
overlap: 0.25
num_of_best_matches: 25

base_noise: 5.0

speed_mps: 5.0
dt_sim: 0.1
