defaults:
  - _self_

work_env:
  seed: 42
  visualize: True
  pre_selection: True
  # picture_path: "data/NAIP/m_3809452_se_15_1_20120624.jpg"
  # picture_path: "data/NAIP/m_3809456_se_15_1_20090719.jpg"
  picture_path: "data/NAIP/m_3608905_nw_16_1_20140728.jpg"
  patch_size: 128
  start: 0
  scale: 1.0

particles:
  number: 150
  rand_static_move: 20

resampler:
  name: "Systematic"

matcher:
  starter: "NN"
  continous: "LBP"
  patch_size: 128
  overlap: 0.25
  num_of_best_matches: 25
uav:
  traj_len: 300

metrics:
  ploting: True

model:
  encoder_name: "resnet50"
  embedding_size: 128
  weights_path: "data/models/model_365.pth"
